name       : libgnt
version    : 2.14.1
release    : 3
source     :
    - https://downloads.sourceforge.net/project/pidgin/libgnt/2.14.1/libgnt-2.14.1.tar.xz : 5ec3e68e18f956e9998d79088b299fa3bca689bcc95c86001bc5da17c1eb4bd8
homepage   : https://keep.imfreedom.org/libgnt/libgnt
license    : GPL-2.0-or-later
component  : programming.library
summary    : GLib NCurses Toolkit
description: |
    GNT is an ncurses toolkit for creating text-mode graphical user interfaces in a fast and easy way. It is based on GLib and ncurses.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libxml-2.0)
    - pkgconfig(ncursesw)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
