name       : libgnt
version    : 2.14.0
release    : 2
source     :
    - https://downloads.sourceforge.net/project/pidgin/libgnt/2.14.0/libgnt-2.14.0.tar.xz : 6b7ea2030c9755ad9756ab4b1d3396dccaef4a712eccce34d3990042bb4b3abf
homepage   : https://keep.imfreedom.org/libgnt/libgnt
license    : GPL-2.0-or-later
component  : programming.library
summary    : GLib NCurses Toolkit
description: |
    GNT is an ncurses toolkit for creating text-mode graphical user interfaces in a fast and easy way. It is based on GLib and ncurses.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libxml-2.0)
    - pkgconfig(ncursesw)
    - pkgconfig(python3)
setup      : |
    sed -i "s|python2|python3|g" meson.build
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
